dist: trusty
sudo: false
addons:
  ssh_known_hosts:
    - 34.229.86.216
language: ruby
rvm:
  - 2.4.1
install: gem install jekyll jekyll-paginate html-proofer
script: jekyll build && htmlproofer ./_site
