dist: trusty
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_462eaa1dcd52_key -iv $encrypted_462eaa1dcd52_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
addons:
  ssh_known_hosts:
  - 34.229.86.216
language: ruby
cache: bundler
rvm:
- 2.4.1
script: "./script/cibuild"
after_success:
- "./script/deploy"
