dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - 34.229.86.216
language: ruby
rvm:
- 2.4.1
script: "./script/cibuild"
after_success:
  - openssl aes-256-cbc -K $encrypted_adce58d55fff_key -iv $encrypted_adce58d55fff_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ./script/deploy
