# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Rüdiger's Blog
tagline:             IPFS, algorithms, data structures
url:                 http://rklaehn.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rüdiger Klaehn
  url:               https://rklaehn.github.io
  email:             rklaehn@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rklaehn/rklaehn.github.io


# Github repositories
github_user: rklaehn
github_repo_count: 5
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user: klaehnr
twitter_tweet_button: true

markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

plugins: [jekyll-paginate]
    